ALTER TABLE TBLDADOSEMPRESA ADD TOKENNFCE VARCHAR(255);
ALTER TABLE TBLDADOSEMPRESA ADD TOKENNFCEID VARCHAR(150);
ALTER TABLE TBLDADOSEMPRESA ADD NROSERIECERTDIGITAL VARCHAR(255);
ALTER TABLE TBLDADOSEMPRESA ADD SENHACERTDIGITAL VARCHAR(150);

