ALTER TABLE TBLCONFIGURACOES
ADD COLUMN IDTOKENNFCE integer,
ADD COLUMN SERIENFCE integer,
ADD COLUMN NROULTIMANFCE intger,
ADD COLUMN SENHACERTDIGITAL VARCHAR(50),
ADD COLUMN TOKENNFCE VARCHAR(255),
ADD COLUMN NROSERIECERTDIGITAL VARCHAR(255)

